name: Beta Release Build

on:
  push:
    tags:
      - 'v*-beta*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      - name: Create beta release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/BulkPurchaseRework.dll
        env:
          GITHUB_TOKEN: ${{ secrets.AutomatedBuild }}
